### ISSUE TITLE
cli: delete batch

### ISSUE THREAD

**Issue by mayabrandi** [Clinical-Genomics/statina#67]
Add to cli: delete batch

Should be in place before summer.

**Comment by Mropat** [comment]
ragarding the cli: the app will be only installed and configured to access the mongo via rest api
Suggest we create the delete endpoint in internal app, or enable it for select users in external app (admins only)
in order to use niptool cli directly, one would have to execute it from within container on specific server, which would be suboptinal

**Comment by mayabrandi** [comment]
Good point

Skickat från min iPhone
